global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'finvest-ai-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend-ai:8000']

  - job_name: 'finvest-spring-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend-spring:8080']
